backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:

  - name: header
    label: Header/Nav
    folder: src/data/header
    extension: json
    fields:
      - name: title
        label: Header/Nav
      - name: links
        label: Links
        widget: list
        fields:
          - name: linkText
            label: Link Text
          - name: path
            label: Path
      - name: fbURL
        label: Facebook URL
      - name: igURL
        label: Instagram URL
      - name: twURL
        label: Twitter URL